// Data for the rich widget reference: per widget, a real-output screenshot (the
// `shot` matches a file in src/generated/shots, generated by the Mire.Shots tool),
// a one-line summary, the F# signature, and a parameter table. Grouped for the page.

export interface Param {
  name: string;
  type: string;
  desc: string;
}

export interface Widget {
  id: string;
  title: string;
  summary: string;
  shot?: string; // filename (no extension) in src/generated/shots
  signature: string;
  params: Param[];
}

export interface Group {
  name: string;
  blurb: string;
  widgets: Widget[];
}

export const GROUPS: Group[] = [
  {
    name: "Text & chrome",
    blurb: "The building blocks — text, borders, and the small labels around your UI.",
    widgets: [
      {
        id: "text",
        title: "Text",
        summary: "Styled text. Splits on newlines and is measured by grapheme width.",
        shot: "text",
        signature: "Text.text (content: string) (style: Style) : LayoutNode<'msg>",
        params: [
          { name: "content", type: "string", desc: "The text. '\\n' starts a new line; widths are grapheme-cluster aware." },
          { name: "style", type: "Style", desc: "Foreground, bold, underline, etc. Use Style.text / a theme field." },
        ],
      },
      {
        id: "box",
        title: "Box & Panel",
        summary: "A single-line border around one child; Panel adds a title row.",
        shot: "panel",
        signature: "Box.box (style: Style) (children: LayoutNode<'msg> list) : LayoutNode<'msg>\nBox.panel (title: string) (style: Style) (children: LayoutNode<'msg> list) : LayoutNode<'msg>",
        params: [
          { name: "title", type: "string", desc: "Panel only — the label shown in the top border row." },
          { name: "style", type: "Style", desc: "The border color (use theme.border / theme.borderFocus)." },
          { name: "children", type: "LayoutNode list", desc: "Box renders one child filling the inner rect; flow several through a Stack." },
        ],
      },
      {
        id: "badge",
        title: "Badge & KeyHint",
        summary: "A pill label and a key+description hint for status bars and help rows.",
        shot: "badges",
        signature: "Badge.badge (style: Style) (label: string) : LayoutNode<'msg>\nKeyHint.hint (keyStyle: Style) (labelStyle: Style) (key: string) (label: string) : LayoutNode<'msg>",
        params: [
          { name: "style", type: "Style", desc: "Badge: pass a background-bearing style (e.g. theme.accentStrong) so the pill reads." },
          { name: "key", type: "string", desc: "KeyHint: the key glyph, e.g. \"⏎\" or \"^C\"." },
          { name: "label", type: "string", desc: "The badge text / the hint description." },
        ],
      },
      {
        id: "statusbar",
        title: "StatusBar",
        summary: "A bordered row with left, center, and right item groups.",
        shot: "statusbar",
        signature: "StatusBar.statusBar (left: LayoutNode<'msg> list) (center: LayoutNode<'msg> list) (right: LayoutNode<'msg> list) : LayoutNode<'msg>",
        params: [
          { name: "left", type: "LayoutNode list", desc: "Items pinned to the left (e.g. a mode badge)." },
          { name: "center", type: "LayoutNode list", desc: "Items in the middle (e.g. the file name)." },
          { name: "right", type: "LayoutNode list", desc: "Items pinned to the right (e.g. a cursor position)." },
        ],
      },
    ],
  },
  {
    name: "Lists & tables",
    blurb: "Virtualized — they build only the visible window of rows, so size is free.",
    widgets: [
      {
        id: "listview",
        title: "ListView",
        summary: "A selectable, scrolling list. Highlights the selection; auto-scrolls to it.",
        shot: "listview",
        signature: "ListView.view (height: int) (selStyle: Style) (rowStyle: Style) (selected: int) (labels: string list) : LayoutNode<'msg>",
        params: [
          { name: "height", type: "int", desc: "Visible rows. Only this many are built, regardless of list length." },
          { name: "selStyle", type: "Style", desc: "Style for the selected row (full-width; use theme.selection)." },
          { name: "rowStyle", type: "Style", desc: "Style for the other rows." },
          { name: "selected", type: "int", desc: "The selected index (app-owned state)." },
          { name: "labels", type: "string list", desc: "The rows. Use viewWith for a predicate (multi-select)." },
        ],
      },
      {
        id: "table",
        title: "Table",
        summary: "A sticky-header table with Length-width columns and per-cell renderers.",
        shot: "table",
        signature: "Table.view (height: int) (headerStyle: Style) (selStyle: Style) (topRow: int) (isSelected: int -> bool) (columns: Column<'row,'msg> list) (rows: 'row list) : LayoutNode<'msg>",
        params: [
          { name: "height", type: "int", desc: "Visible body rows (windowed from topRow)." },
          { name: "topRow", type: "int", desc: "First visible row — the scroll offset." },
          { name: "isSelected", type: "int -> bool", desc: "Per-row highlight predicate (single or multi-select)." },
          { name: "columns", type: "Column list", desc: "Build with Table.textColumn header width style toStr; Render can return any node." },
          { name: "rows", type: "'row list", desc: "The data; columns project each row to cells." },
        ],
      },
    ],
  },
  {
    name: "Inputs",
    blurb: "Render over a TextBuffer. Pure edit logic lives in TextBuffer / TextEdit.",
    widgets: [
      {
        id: "input",
        title: "Input & TextArea",
        summary: "Single-line and multi-line editors. Block cursor, selection highlight, soft-wrap.",
        shot: "input",
        signature: "Input.render (width: int) (textStyle: Style) (cursorStyle: Style) (focused: bool) (buf: TextBuffer) : LayoutNode<'msg>\nTextArea.renderWrapped (width: int) (height: int) (textStyle: Style) (cursorStyle: Style) (focused: bool) (buf: TextBuffer) : LayoutNode<'msg>",
        params: [
          { name: "width / height", type: "int", desc: "The cell box. Input scrolls horizontally to the cursor; renderWrapped word-wraps." },
          { name: "cursorStyle", type: "Style", desc: "The block cursor and the selection highlight (inverse video reads as selected)." },
          { name: "focused", type: "bool", desc: "Draw the cursor / selection only when focused." },
          { name: "buf", type: "TextBuffer", desc: "Text + cursor + selection (app-owned). See the editing guide." },
        ],
      },
    ],
  },
  {
    name: "Overlays",
    blurb: "Layers you stack over a base tree with LayoutNode.Overlay.",
    widgets: [
      {
        id: "modal",
        title: "Modal",
        summary: "A centered box with its own dimming backdrop.",
        shot: "modal",
        signature: "Modal.modal (backdropStyle: Style) (borderStyle: Style) (titleStyle: Style) (width: int) (height: int) (title: string) (body: LayoutNode<'msg>) : LayoutNode<'msg>",
        params: [
          { name: "backdropStyle", type: "Style", desc: "The full-screen dim behind the box (Style.Default for a plain dim)." },
          { name: "width / height", type: "int", desc: "The centered box size, in cells." },
          { name: "title", type: "string", desc: "Shown in the top row." },
          { name: "body", type: "LayoutNode<'msg>", desc: "The modal contents (one node; flow with a Stack)." },
        ],
      },
      {
        id: "completion",
        title: "Completion",
        summary: "A cursor-anchored, bordered suggestion list that clamps on-screen.",
        shot: "completion",
        signature: "Completion.view (areaW: int) (areaH: int) (anchorX: int) (anchorY: int) (width: int) (maxRows: int) (borderStyle: Style) (selStyle: Style) (rowStyle: Style) (selected: int) (items: string list) : LayoutNode<'msg>",
        params: [
          { name: "areaW / areaH", type: "int", desc: "The screen size, so the popup can clamp itself on-screen." },
          { name: "anchorX / anchorY", type: "int", desc: "The caret position to anchor below (flips above when low on space)." },
          { name: "width / maxRows", type: "int", desc: "Popup width and the most rows to show." },
          { name: "selected", type: "int", desc: "The highlighted item; items is the filtered candidate list." },
        ],
      },
    ],
  },
  {
    name: "Status & controls",
    blurb: "Spinners, progress, tabs, and toggles — pure render, app-owned state.",
    widgets: [
      {
        id: "controls",
        title: "ProgressBar · Spinner · Toggle",
        summary: "A fill bar, an animated braille spinner, and checkbox/radio/switch glyphs.",
        shot: "controls",
        signature: "ProgressBar.view (width: int) (fillStyle: Style) (trackStyle: Style) (fraction: float) : LayoutNode<'msg>\nSpinner.labeled (spinStyle: Style) (labelStyle: Style) (tick: int) (label: string) : LayoutNode<'msg>\nToggle.switch (onStyle: Style) (offStyle: Style) (isOn: bool) : LayoutNode<'msg>",
        params: [
          { name: "fraction", type: "float", desc: "ProgressBar fill, 0.0–1.0 (clamped)." },
          { name: "tick", type: "int", desc: "Spinner frame index — drive it from a Sub.Every counter." },
          { name: "isOn / isChecked / selected", type: "bool", desc: "Toggle state (switch / checkbox / radio)." },
        ],
      },
      {
        id: "tabs",
        title: "Tabs",
        summary: "A horizontal label strip with one active tab.",
        shot: "tabs",
        signature: "Tabs.strip (activeStyle: Style) (inactiveStyle: Style) (selected: int) (labels: string list) : LayoutNode<'msg>",
        params: [
          { name: "selected", type: "int", desc: "Index of the active tab (app-owned)." },
          { name: "labels", type: "string list", desc: "The tab labels." },
        ],
      },
    ],
  },
  {
    name: "Media",
    blurb: "Images and markdown.",
    widgets: [
      {
        id: "imagepreview",
        title: "ImagePreview",
        summary: "A portable, captioned placeholder; overlay real pixels with Cmd.kittyImage.",
        shot: "imagepreview",
        signature: "ImagePreview.render (width: int) (height: int) (borderStyle: Style) (captionStyle: Style) (caption: string) (pixelSize: (int * int) option) : LayoutNode<'msg>",
        params: [
          { name: "width / height", type: "int", desc: "The placeholder box size, in cells." },
          { name: "caption", type: "string", desc: "Shown under the icon (e.g. a filename)." },
          { name: "pixelSize", type: "(int*int) option", desc: "Optional WxH, shown as e.g. 640×480 when known." },
        ],
      },
      {
        id: "markdown",
        title: "Markdown",
        summary: "Renders headings, lists, code, quotes, and OSC 8 links to a node.",
        shot: "markdown",
        signature: "Markdown.render (style: MarkdownStyle) (width: int) (src: string) : LayoutNode<'msg>",
        params: [
          { name: "style", type: "MarkdownStyle", desc: "Heading / code / link styling. Use theme.markdown." },
          { name: "width", type: "int", desc: "Wrap width in cells." },
          { name: "src", type: "string", desc: "The markdown source." },
        ],
      },
    ],
  },
  {
    name: "Agent layer",
    blurb: "From the optional Mire.Agent package — see the agent-layer reference.",
    widgets: [
      {
        id: "transcript",
        title: "ChatTranscript",
        summary: "A virtualized chat/agent transcript: messages, tool calls, diffs, notices.",
        shot: "transcript",
        signature: "ChatTranscript.view (theme: AppTheme) (wrapWidth: int) (frame: int) (viewportH: int) (offset: int) (trackStyle: Style) (thumbStyle: Style) (blocks: TranscriptBlock list) : LayoutNode<'msg>",
        params: [
          { name: "wrapWidth", type: "int", desc: "Markdown / content wrap width." },
          { name: "frame", type: "int", desc: "Spinner tick, so running tool calls animate." },
          { name: "viewportH / offset", type: "int", desc: "Visible rows and the scroll offset (app-owned; follow the tail with toBottom)." },
          { name: "blocks", type: "TranscriptBlock list", desc: "User/assistant/tool/diff/notice blocks — newest last." },
        ],
      },
    ],
  },
];
