// Data for the widget reference: a grid index of cards (src/pages/.../widgets index)
// plus a detail page per widget (src/pages/docs/reference/widgets/[id].astro). Each
// `shot` matches a file in src/generated/shots (generated by the Mire.Shots tool).

export interface Param {
  name: string;
  type: string;
  desc: string;
}

export interface Related {
  href: string;
  label: string;
}

export interface Widget {
  id: string;
  title: string;
  summary: string;
  shot?: string; // filename (no extension) in src/generated/shots
  signature: string; // F#, multi-line
  params: Param[];
  details?: string; // a longer paragraph for the detail page
  example?: string; // F# usage snippet
  related?: Related[];
}

export interface Group {
  name: string;
  blurb: string;
  widgets: Widget[];
}

export const GROUPS: Group[] = [
  {
    name: "Text & chrome",
    blurb: "The building blocks — text, borders, and the small labels around your UI.",
    widgets: [
      {
        id: "text",
        title: "Text",
        summary: "Styled text. Splits on newlines and is measured by grapheme width.",
        shot: "text",
        signature: `Text.text (content: string) (style: Style) : LayoutNode<'msg>
Text.title (content: string) : LayoutNode<'msg>
Text.dimText (content: string) : LayoutNode<'msg>`,
        params: [
          { name: "content", type: "string", desc: "The text. A '\\n' starts a new line; widths are grapheme-cluster aware." },
          { name: "style", type: "Style", desc: "Foreground, bold, underline, and so on. Use Style.text or a theme field." },
        ],
        details:
          "Text is the leaf of almost every view. It measures its content by display width (grapheme clusters, so wide CJK and emoji count correctly) and clips to its assigned rect. `Text.title` and `Text.dimText` are shorthands for the branded title and muted styles.",
        example: `Stack.vstack
    [ Text.title "Report"
      Text.text "All checks passed." theme.success
      Text.dimText "updated just now" ]`,
        related: [{ href: "/docs/reference/styling/", label: "Color, Style, and AppTheme" }],
      },
      {
        id: "box",
        title: "Box & Panel",
        summary: "A single-line border around one child; Panel adds a title row.",
        shot: "panel",
        signature: `Box.box (style: Style) (children: LayoutNode<'msg> list) : LayoutNode<'msg>
Box.panel (title: string) (style: Style) (children: LayoutNode<'msg> list) : LayoutNode<'msg>`,
        params: [
          { name: "title", type: "string", desc: "Panel only — the label drawn into the top border." },
          { name: "style", type: "Style", desc: "The border color. Use theme.border, or theme.borderFocus for a focused pane." },
          { name: "children", type: "LayoutNode list", desc: "Box renders one child filling the inner rect; flow several through a Stack." },
        ],
        details:
          "A Box draws a border and gives its inner rect to a single child — pass multiple children and they overlap, so wrap them in a `Stack`. Swap the border style for `theme.borderFocus` to show which pane has focus.",
        example: `Box.panel "settings" theme.border
    [ Toggle.checkbox theme.fg true "wrap lines"
      Toggle.checkbox theme.fg false "show line numbers" ]`,
        related: [{ href: "/docs/reference/layout/", label: "Layout nodes" }],
      },
      {
        id: "badge",
        title: "Badge & KeyHint",
        summary: "A pill label and a key+description hint for status bars and help rows.",
        shot: "badges",
        signature: `Badge.badge (style: Style) (label: string) : LayoutNode<'msg>
KeyHint.hint (keyStyle: Style) (labelStyle: Style) (key: string) (label: string) : LayoutNode<'msg>`,
        params: [
          { name: "style", type: "Style", desc: "Badge: pass a background-bearing style (e.g. theme.accentStrong) so the pill reads." },
          { name: "key", type: "string", desc: "KeyHint: the key glyph, e.g. \"⏎\" or \"^C\"." },
          { name: "label", type: "string", desc: "The badge text, or the hint's description." },
        ],
        example: `Stack.hstack
    [ Badge.badge theme.accentStrong "NEW"
      Text.text "   " theme.fg
      KeyHint.hint theme.key theme.fgMuted "^S" "save" ]`,
      },
      {
        id: "statusbar",
        title: "StatusBar",
        summary: "A bordered row with left, center, and right item groups.",
        shot: "statusbar",
        signature: `StatusBar.statusBar
    (left: LayoutNode<'msg> list)
    (center: LayoutNode<'msg> list)
    (right: LayoutNode<'msg> list)
    : LayoutNode<'msg>`,
        params: [
          { name: "left", type: "LayoutNode list", desc: "Items pinned to the left (e.g. a mode badge)." },
          { name: "center", type: "LayoutNode list", desc: "Items in the middle (e.g. the file name)." },
          { name: "right", type: "LayoutNode list", desc: "Items pinned to the right (e.g. a cursor position)." },
        ],
        example: `StatusBar.statusBar
    [ Text.text "NORMAL" theme.accent ]
    [ Text.text "main.fs" theme.fgMuted ]
    [ Text.text "ln 1, col 1" theme.fgSubtle ]`,
      },
    ],
  },
  {
    name: "Lists & tables",
    blurb: "Virtualized — they build only the visible window of rows, so size is free.",
    widgets: [
      {
        id: "listview",
        title: "ListView",
        summary: "A selectable, scrolling list. Highlights the selection and auto-scrolls to it.",
        shot: "listview",
        signature: `ListView.view
    (height: int)
    (selStyle: Style)
    (rowStyle: Style)
    (selected: int)
    (labels: string list)
    : LayoutNode<'msg>

ListView.viewWith
    (height: int) (selStyle: Style) (rowStyle: Style)
    (isSelected: int -> bool) (scrollTo: int) (labels: string list)
    : LayoutNode<'msg>`,
        params: [
          { name: "height", type: "int", desc: "Visible rows. Only this many are built, whatever the list length." },
          { name: "selStyle", type: "Style", desc: "Style for the selected row (drawn full-width; use theme.selection)." },
          { name: "rowStyle", type: "Style", desc: "Style for the other rows." },
          { name: "selected", type: "int", desc: "The selected index (your model owns it)." },
          { name: "labels", type: "string list", desc: "The rows. Use viewWith with a predicate for multi-selection." },
        ],
        details:
          "Only the visible window of rows is built, so a million-row list costs the same as a ten-row one. The widget renders and highlights; the selection index and key handling live in your model. `viewWith` takes a predicate (for single or multi-select) plus a `scrollTo` row to keep in view.",
        example: `ListView.view 10 theme.selection theme.fg model.Selected
    (model.Items |> List.map (fun i -> i.Name))`,
        related: [
          { href: "/docs/tutorials/task-list/", label: "Tutorial: build a task list" },
          { href: "/docs/reference/widgets/table/", label: "Table" },
        ],
      },
      {
        id: "table",
        title: "Table",
        summary: "A sticky-header table with Length-width columns and per-cell renderers.",
        shot: "table",
        signature: `Table.view
    (height: int)
    (headerStyle: Style)
    (selStyle: Style)
    (topRow: int)
    (isSelected: int -> bool)
    (columns: Column<'row, 'msg> list)
    (rows: 'row list)
    : LayoutNode<'msg>

Table.textColumn (header: string) (width: Length) (style: Style) (toStr: 'row -> string) : Column<'row, 'msg>`,
        params: [
          { name: "height", type: "int", desc: "Visible body rows (windowed from topRow)." },
          { name: "topRow", type: "int", desc: "First visible row — the scroll offset." },
          { name: "isSelected", type: "int -> bool", desc: "Per-row highlight predicate (single or multi-select)." },
          { name: "columns", type: "Column list", desc: "Build with Table.textColumn; a column's Render can return any node, not just text." },
          { name: "rows", type: "'row list", desc: "The data; the columns project each row to cells." },
        ],
        details:
          "Rows are virtualized through `topRow`/`height`. A selected row is drawn in the selection style across every column (so the highlight is uniform and readable even where a column carries its own color). Because `Column.Render` returns a `LayoutNode`, a cell can be a badge or a progress bar, not only text.",
        example: `let columns =
    [ Table.textColumn "file"   (Length.Cells 20) theme.fg      (fun r -> r.File)
      Table.textColumn "status" (Length.Cells 12) theme.fgMuted (fun r -> r.Status) ]

Table.view 12 theme.fgSubtle theme.selection model.Top
    (fun i -> i = model.Selected) columns model.Rows`,
        related: [{ href: "/docs/reference/widgets/listview/", label: "ListView" }],
      },
    ],
  },
  {
    name: "Inputs",
    blurb: "Render over a TextBuffer. The pure edit logic lives in TextBuffer / TextEdit.",
    widgets: [
      {
        id: "input",
        title: "Input & TextArea",
        summary: "Single-line and multi-line editors: block cursor, selection highlight, soft-wrap.",
        shot: "input",
        signature: `Input.render
    (width: int) (textStyle: Style) (cursorStyle: Style)
    (focused: bool) (buf: TextBuffer)
    : LayoutNode<'msg>

TextArea.renderWrapped
    (width: int) (height: int) (textStyle: Style) (cursorStyle: Style)
    (focused: bool) (buf: TextBuffer)
    : LayoutNode<'msg>`,
        params: [
          { name: "width / height", type: "int", desc: "The cell box. Input scrolls horizontally to the cursor; renderWrapped word-wraps." },
          { name: "cursorStyle", type: "Style", desc: "The block cursor and the selection highlight (inverse video reads as selected)." },
          { name: "focused", type: "bool", desc: "Draw the cursor and selection only when focused." },
          { name: "buf", type: "TextBuffer", desc: "Text, cursor, and selection — your model owns it." },
        ],
        details:
          "Both render a `TextBuffer`; the editing itself is the pure `TextBuffer`/`TextEdit` stack. `Input` scrolls horizontally to keep the cursor visible; `TextArea.render` scrolls both axes; `TextArea.renderWrapped` word-wraps each line and scrolls over the visual rows.",
        example: `// in update: feed input events through the keymap
{ m with Buffer = TextEdit.applyInput e m.Buffer }

// in view:
Input.render 40 theme.fg theme.selection m.Focused m.Buffer`,
        related: [{ href: "/docs/how-to/edit-text/", label: "How-to: edit text" }],
      },
    ],
  },
  {
    name: "Overlays",
    blurb: "Layers you stack over a base tree with LayoutNode.Overlay.",
    widgets: [
      {
        id: "modal",
        title: "Modal",
        summary: "A centered box with its own dimming backdrop.",
        shot: "modal",
        signature: `Modal.modal
    (backdropStyle: Style)
    (borderStyle: Style)
    (titleStyle: Style)
    (width: int) (height: int)
    (title: string)
    (body: LayoutNode<'msg>)
    : LayoutNode<'msg>`,
        params: [
          { name: "backdropStyle", type: "Style", desc: "The full-screen dim behind the box (Style.Default for no dim)." },
          { name: "width / height", type: "int", desc: "The centered box size, in cells." },
          { name: "title", type: "string", desc: "Shown in the top row." },
          { name: "body", type: "LayoutNode<'msg>", desc: "The modal contents (one node; flow several through a Stack)." },
        ],
        details:
          "Layer the modal over your base tree with `LayoutNode.Overlay`, gated on your model. The modal consumes nothing on its own — your `update` decides what Enter/Esc do while it is open. Make its buttons clickable with `Focusable.region` + `withMouseRegion`.",
        example: `LayoutNode.Overlay(Rect.Create(0, 0, 0, 0),
    [ baseTree
      Modal.modal Style.Default theme.border theme.title 44 9 "Confirm"
          (Text.text "Apply 3 changes?" theme.fg) ])`,
        related: [{ href: "/docs/how-to/overlays-and-modals/", label: "How-to: overlays and modals" }],
      },
      {
        id: "completion",
        title: "Completion",
        summary: "A cursor-anchored, bordered suggestion list that clamps on-screen.",
        shot: "completion",
        signature: `Completion.view
    (areaW: int) (areaH: int)
    (anchorX: int) (anchorY: int)
    (width: int) (maxRows: int)
    (borderStyle: Style) (selStyle: Style) (rowStyle: Style)
    (selected: int) (items: string list)
    : LayoutNode<'msg>`,
        params: [
          { name: "areaW / areaH", type: "int", desc: "The screen size, so the popup can clamp itself on-screen." },
          { name: "anchorX / anchorY", type: "int", desc: "The caret position; the popup sits below it, flipping above when low on space." },
          { name: "width / maxRows", type: "int", desc: "Popup width and the most rows to show." },
          { name: "selected", type: "int", desc: "The highlighted item; items is your filtered candidate list." },
        ],
        details:
          "You filter the candidates and track the selection; the widget places and draws the popup. For a Ctrl+P command surface use `CommandPalette.view`; `CommandPalette.filter query candidates` is the reusable fuzzy ranker.",
        related: [{ href: "/docs/how-to/overlays-and-modals/", label: "How-to: overlays and modals" }],
      },
    ],
  },
  {
    name: "Status & controls",
    blurb: "Spinners, progress, tabs, and toggles — pure render, app-owned state.",
    widgets: [
      {
        id: "controls",
        title: "ProgressBar · Spinner · Toggle",
        summary: "A fill bar, an animated braille spinner, and checkbox/radio/switch glyphs.",
        shot: "controls",
        signature: `ProgressBar.view (width: int) (fillStyle: Style) (trackStyle: Style) (fraction: float) : LayoutNode<'msg>
Spinner.labeled (spinStyle: Style) (labelStyle: Style) (tick: int) (label: string) : LayoutNode<'msg>
Toggle.checkbox (style: Style) (isChecked: bool) (label: string) : LayoutNode<'msg>
Toggle.switch (onStyle: Style) (offStyle: Style) (isOn: bool) : LayoutNode<'msg>`,
        params: [
          { name: "fraction", type: "float", desc: "ProgressBar fill, 0.0–1.0 (clamped)." },
          { name: "tick", type: "int", desc: "Spinner frame index — advance it from a Sub.Every counter." },
          { name: "isOn / isChecked", type: "bool", desc: "Toggle state (switch / checkbox; Toggle.radio is the same shape)." },
        ],
        details:
          "All are pure functions of state you hold. To animate the spinner, increment a tick on a `Sub.Every` and pass it in. `Toggle` ships `checkbox`, `radio`, and `switch`.",
        example: `// subscriptions: tick four times a second while busy
[ Sub.Every(TimeSpan.FromMilliseconds 250.0, fun () -> Tick) ]

// view:
Spinner.labeled theme.accent theme.fgMuted model.Tick "working…"`,
      },
      {
        id: "tabs",
        title: "Tabs",
        summary: "A horizontal label strip with one active tab.",
        shot: "tabs",
        signature: `Tabs.strip
    (activeStyle: Style) (inactiveStyle: Style)
    (selected: int) (labels: string list)
    : LayoutNode<'msg>`,
        params: [
          { name: "selected", type: "int", desc: "Index of the active tab (your model owns it)." },
          { name: "labels", type: "string list", desc: "The tab labels." },
        ],
        example: `Tabs.strip theme.accentStrong theme.fgMuted model.Tab
    [ "Files"; "Search"; "Git" ]`,
      },
    ],
  },
  {
    name: "Media",
    blurb: "Images and markdown.",
    widgets: [
      {
        id: "imagepreview",
        title: "ImagePreview",
        summary: "A portable, captioned placeholder; overlay real pixels with Cmd.kittyImage.",
        shot: "imagepreview",
        signature: `ImagePreview.render
    (width: int) (height: int)
    (borderStyle: Style) (captionStyle: Style)
    (caption: string) (pixelSize: (int * int) option)
    : LayoutNode<'msg>`,
        params: [
          { name: "width / height", type: "int", desc: "The placeholder box size, in cells." },
          { name: "caption", type: "string", desc: "Shown under the icon (e.g. a filename)." },
          { name: "pixelSize", type: "(int * int) option", desc: "Optional WxH, shown as e.g. 640×480 when known." },
        ],
        details:
          "This renders the portable placeholder that shows on every terminal. On Kitty/Ghostty, overlay the real pixels with `Cmd.kittyImage` positioned at the placeholder's coordinates — Mire never decodes images, so you supply encoded bytes.",
        related: [{ href: "/docs/how-to/show-images/", label: "How-to: show an image" }],
      },
      {
        id: "markdown",
        title: "Markdown",
        summary: "Renders headings, lists, code, quotes, and OSC 8 links to a node.",
        shot: "markdown",
        signature: `Markdown.render (style: MarkdownStyle) (width: int) (src: string) : LayoutNode<'msg>
Markdown.wrap (style: MarkdownStyle) (width: int) (baseStyle: Style) (text: string) : LayoutNode<'msg>`,
        params: [
          { name: "style", type: "MarkdownStyle", desc: "Heading / code / link styling. Use theme.markdown." },
          { name: "width", type: "int", desc: "Wrap width, in cells." },
          { name: "src", type: "string", desc: "The markdown source." },
        ],
        details:
          "Renders a useful subset — headings, lists, code, block quotes, and links — to a layout node. Links carry their real URL as an OSC 8 hyperlink, clickable in terminals that support it.",
        example: `Markdown.render theme.markdown 60
    "# Done\\n\\nBuilt **2 targets** in \`1.1s\`."`,
      },
    ],
  },
  {
    name: "Agent layer",
    blurb: "From the optional Mire.Agent package — see the agent-layer reference.",
    widgets: [
      {
        id: "transcript",
        title: "ChatTranscript",
        summary: "A virtualized chat/agent transcript: messages, tool calls, diffs, and notices.",
        shot: "transcript",
        signature: `ChatTranscript.view
    (theme: AppTheme)
    (wrapWidth: int) (frame: int)
    (viewportH: int) (offset: int)
    (trackStyle: Style) (thumbStyle: Style)
    (blocks: TranscriptBlock list)
    : LayoutNode<'msg>`,
        params: [
          { name: "wrapWidth", type: "int", desc: "Markdown / content wrap width." },
          { name: "frame", type: "int", desc: "A spinner tick, so running tool calls animate." },
          { name: "viewportH / offset", type: "int", desc: "Visible rows and the scroll offset (yours; follow the tail with toBottom)." },
          { name: "blocks", type: "TranscriptBlock list", desc: "User / assistant / tool / diff / notice blocks — newest last." },
        ],
        details:
          "Only the blocks intersecting the viewport are built, while the scrollbar reflects the true content height. The offset is your state; `ChatTranscript.toBottom`/`atBottom`/`clampOffset` make following the tail a one-liner in `update`.",
        related: [{ href: "/docs/reference/agent-layer/", label: "The agent layer" }],
      },
    ],
  },
];

// Flat, in-order list — for the grid, prev/next, and the [id] route.
export const ALL_WIDGETS: Widget[] = GROUPS.flatMap((g) => g.widgets);

export const widgetById = (id: string): Widget | undefined =>
  ALL_WIDGETS.find((w) => w.id === id);
